[package]
name = "prism_movement_escrow"
version = "1.0.0"

[addresses]
prism_addr = "0x89c72c2fc93fe01b31a316b24df41f2da84a9ffc"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "mainnet" }
